title: M0rt-P@ge$$$ 
description: "August 2023 to June 2024"
owner_name: Tirth Thakkar
github_username: Tirth-Thakkar
github_repo: "Mort-Pages"
baseurl: "/Mort-Pages"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/Tirth-Thakkar"}

# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
